### PR TITLE
IE7 and iframeTarget fixes

### PR DESCRIPTION
**Pull request by emasab**
Hi malsup, here is the pull request that you asked me. Sorry for the delay, but I was kind of busy.

### CODE REVIEW

**Comment by kevindb** [comment]
Is this PR still necessary?

Possibly related to [#358 custom iframeTarget doesn't attach load listener](https://github.com/jquery-form/form/issues/358)
Possibly resolved by d0e782f

**Comment by emasab** [comment]
for the ownerDocument thing, The problem was that 
http://stackoverflow.com/questions/2284356/cant-appendchild-to-a-node-created-from-another-frame
maybe it's present in IE10 too, because here states
https://msdn.microsoft.com/en-us/library/gg592979(v=vs.85).aspx

The node is owned by a different document and cannot be used. Starting with Internet Explorer 10, the error-code string WrongDocumentError is returned instead.

It usually happens when using jQuery from the opener window and the form is in the opened window.

The move of 
if (io.attachEvent)
is necessary for the custom iframeTarget

**Comment by kevindb** [comment]
Whew! This gets messy with a four year old PR. It looks like d0e782f (8 months after your PR) took care of moving `if (io.attachEvent)`.

Would you please update your PR (or create a new one, if that's easier) from current `master` for your `form.ownerDocument` and `$form.closest('body')` changes?

**Comment by emasab** [comment]
here is the new PR

https://github.com/jquery-form/form/pull/518

**Pull request closed without merging**
