### PR TITLE
Provide minified version.

### PR DESCRIPTION
**Pull request by ericduran**
I know it takes 2 seconds for anyone to actually minified the code.

But it would be nice if there was one already provided :)

### CODE REVIEW

**Comment by cobexer** [comment]
This would only clutter the history, diffs, and make merging harder.
What benefit would a minified version have?

**Comment by ericduran** [comment]
@cobexer I don't understand how this will cutter the history,diff, etc..

The minified version should only be on tag releases like 2.0, 2.1, etc. Assuming the versions are being tag, even though it doesn't look like it.

Is really only for convenience.

**Comment by cobexer** [comment]
To achieve that @malsup would need to do the following for every commit (since here every commit is a release version):
- commit the change,
- branch from that commit
- add a minified version in that branch
- tag the commit that added the minified version
- (delete the branch that was only made to add the minified version to not clutter the main history)

looking at the diff between one version and another would always contain the minified version too

all for the benefit that lazy people get a pre minified version from the source repository.
I consider those people lazy because they are most likely using that minified version and add is as a separate script tag to their site/app. they should however minify all scripts they use into one single script and for that purpose it doesn't matter if the jquery.form.js is pre minified or not. actually it would be bad because if they only have the minified version debugging any issues they might encounter is nearly impossible...

 and now this pull request is obsolete because there where 3 commits in this repository...

**Comment by malsup** [comment]
Requesting a minified code version does not imply that someone is lazy.  Keep it real.  If anyone is lazy it's me because I really don't want to minify on every commit and I don't use tags or releases.  I certainly would not have to go through the steps outlined by cobexer, I'd just need to commit two files instead of one, but still I'd rather not do that.

**Comment by cobexer** [comment]
I didn't mean to accuse anyone of you as being lazy, I just wanted to point out that including a minified version into the source repository is a bad idea for multiple reasons.

**Comment by ericduran** [comment]
:-) I understand no worries, I'll just keep minifying it myself :)

Sorry for the bother.

**Comment by garfbradaz** [comment]
Just do it yourself 

http://www.refresh-sf.com/yui/

**Pull request closed without merging**
