### PR TITLE
Xhr upload file

### PR DESCRIPTION
**Pull request by francois2metz**
Hi,

We have added support of xmlhttprequest level 2 with FormData object. We can now upload files using xmlhttprequest.

Furthermore, you can provide callback in order to listen the upload progress events.

Feedback is welcome !

François

### CODE REVIEW

**Comment by malsup** [comment]
Thanks François, I'll definitely check this out!

**Comment by ThiefMaster** [comment]
Any ETA when FormData fileuploads will be available?

**Comment by ghost** [comment]
Looking forward to this pull

**Comment by Pezmc** [comment]
Still haven't been accepted?

**Comment by malsup** [comment]
Finally added this capability (v2.90).  Unfortunately, recent jQuery versions do not expose the 'upload' property of the XHR so progress tracking in not possible until that is fixed.

**Pull request closed without merging**
