### PR TITLE
dataAlter callback

### PR DESCRIPTION
**Pull request by jeffreymb**
In my situation I needed to submit the data to the server in a specially crafted JSON string. To accomplish this I needed a way to directly alter the data before it was sent.

### CODE REVIEW

**Comment by malsup** [comment]
Why not just use the "beforeSubmit" callback?

**Comment by jeffreymb** [comment]
I can manipulate options.data in the beforeSubmit callback but anything I change will be overwritten by line 123 ("options.data = q;").

**Comment by malsup** [comment]
Your change is inserted right after beforeSubmit. How is that any different?

**Comment by jeffreymb** [comment]
I guess you are right. I had missed the fact that "a" was passed to "beforeSubmit". I was attempting to work with options.data which is overwritten as I mentioned earlier. So, all that I have to do is alter "a" in my "beforeSubmit" handler...Thanks for the help and sorry for taking your time!

**Comment by malsup** [comment]
No worries.  Cheers!

**Pull request closed without merging**
