### PR TITLE
Generalization for all REST API

### PR DESCRIPTION
**Pull request by gcusnieux**
Recovery enctype of the form, remove the static 'multipart/form'.. there may be other types such as 'multipart/related' & taking into account the contentType 'options' because for some REST API, the contentType is mandatory

### CODE REVIEW

**Comment by malsup** [comment]
Can you provide a cleaner patch that doesn't reformat the entire file?

**Comment by hugohenrique** [comment]
ping

**Comment by kevindb** [comment]
@gcusnieux, I have a few questions for you about this PR:
1. Can you provide documentation about other possible values for the `form` `enctype` attribute? [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-enctype) only list three: `application/x-www-form-urlencoded`, `multipart/form-data`, and `text/plain`.
2. What is the significance of checking the value of an `encoding` attribute on the form ([line 181](https://github.com/jquery-form/form/pull/295/files?w=1#diff-d4883ec540718940a69b40787716c501R181))? I haven't been able to find any documentation that it is a valid attribute for the `form` tag.
3. Why did you remove the `contentType` default (false) from [line 255](https://github.com/jquery-form/form/pull/295/files?w=1#diff-d4883ec540718940a69b40787716c501L255)?

**Comment by kevindb** [comment]
I am closing this PR for now. It can be reopened if there is demand for this feature.

**Pull request closed without merging**
